// create separate namespace for all the Emscripten stuff.. otherwise naming clashes may occur especially when 
// optimizing using closure compiler..
window.spp_backend_state_mdx= {
	locateFile: function(path, scriptDirectory) { return (typeof window.WASM_SEARCH_PATH == 'undefined') ? path : window.WASM_SEARCH_PATH + path; },
	notReady: true,
	adapterCallback: function(){}	// overwritten later	
};
window.spp_backend_state_mdx["onRuntimeInitialized"] = function() {	// emscripten callback needed in case async init is used (e.g. for WASM)
	this.notReady= false;
	this.adapterCallback();
}.bind(window.spp_backend_state_mdx);

var backend_mdx = (function(Module) {var d;d||(d=typeof Module !== 'undefined' ? Module : {});var aa={},h;for(h in d)d.hasOwnProperty(h)&&(aa[h]=d[h]);d.arguments=[];d.thisProgram="./this.program";d.quit=function(a,b){throw b;};d.preRun=[];d.postRun=[];var ba=!1,k=!1,l=!1,ca=!1;ba="object"===typeof window;k="function"===typeof importScripts;l="object"===typeof process&&"function"===typeof require&&!ba&&!k;ca=!ba&&!l&&!k;
if(d.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");assert("undefined"===typeof d.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof d.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"===typeof d.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof d.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");var n="";function da(a){return d.locateFile?d.locateFile(a,n):n+a}
if(l){n=__dirname+"/";var ea,fa;d.read=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);a=ea.readFileSync(a);return b?a:a.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(d.thisProgram=process.argv[1].replace(/\\/g,"/"));d.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=d);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",
p);d.quit=function(a){process.exit(a)};d.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(d.read=function(a){return read(a)}),d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===typeof quit&&(d.quit=function(a){quit(a)});else if(ba||k)k?
n=self.location.href:document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",d.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),d.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==
e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},d.setWindowTitle=function(a){document.title=a};else throw Error("environment detection error");var ha=d.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),r=d.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(h in aa)aa.hasOwnProperty(h)&&(d[h]=aa[h]);aa=void 0;u=ia=ja=ka=function(){p("cannot use the stack before compiled code is ready to run, and has provided stack access")};
function la(a){assert(!ma);var b=v;v=v+a+15&-16;assert(v<w,"not enough memory for static allocation - increase TOTAL_MEMORY");return b}function na(a){var b;b||(b=16);return Math.ceil(a/b)*b}var oa,qa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};function ra(a){switch(a){case 1:return"i8";case 2:return"i16";case 4:return"i32";case 8:return"double";default:assert(0)}}
function sa(a,b,c){0>=a&&p("segmentation fault storing "+c+" bytes to address "+a);0!==a%c&&p("alignment error storing to address "+a+", which was expected to be aligned to a multiple of "+c);ma?(a+c>x[y>>2]&&p("segmentation fault, exceeded the top of the available dynamic heap when storing "+c+" bytes to address "+a+". STATICTOP="+v+", DYNAMICTOP="+x[y>>2]),assert(y),assert(x[y>>2]<=w)):a+c>v&&p("segmentation fault, exceeded the top of the available static heap when storing "+c+" bytes to address "+
a+". STATICTOP="+v);c=(c=ra(c))||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":z[a>>0]=b;break;case "i8":z[a>>0]=b;break;case "i16":ta[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":tempI64=[b>>>0,(tempDouble=b,1<=+ua(tempDouble)?0<tempDouble?(va(+wa(tempDouble/4294967296),4294967295)|0)>>>0:~~+xa((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];x[a>>2]=tempI64[0];x[a+4>>2]=tempI64[1];break;case "float":ya[a>>2]=b;break;case "double":za[a>>3]=b;break;default:p("invalid type for setValue: "+
c)}}
function A(a,b,c){0>=a&&p("segmentation fault loading "+b+" bytes from address "+a);0!==a%b&&p("alignment error loading from address "+a+", which was expected to be aligned to a multiple of "+b);ma?(a+b>x[y>>2]&&p("segmentation fault, exceeded the top of the available dynamic heap when loading "+b+" bytes from address "+a+". STATICTOP="+v+", DYNAMICTOP="+x[y>>2]),assert(y),assert(x[y>>2]<=w)):a+b>v&&p("segmentation fault, exceeded the top of the available static heap when loading "+b+" bytes from address "+a+
". STATICTOP="+v);b=ra(b);a=Aa(a,b);c&&(c=parseInt(b.substr(1)),a=0<=a?a:32>=c?2*Math.abs(1<<c-1)+a:Math.pow(2,c)+a);return a}var Ba=!1;function assert(a,b){a||p("Assertion failed: "+b)}
var Da={stackSave:function(){u()},stackRestore:function(){ia()},arrayToC:function(a){var b=ja(a.length);assert(0<=a.length,"writeArrayToMemory array must have a length (should be an array or typed array)");z.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1,e=b=ja(c);assert("number"==typeof c,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");Ca(a,D,e,c)}return b}},Ea={string:Da.stringToC,
array:Da.arrayToC};function Aa(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return z[a>>0];case "i8":return z[a>>0];case "i16":return ta[a>>1];case "i32":return x[a>>2];case "i64":return x[a>>2];case "float":return ya[a>>2];case "double":return za[a>>3];default:p("invalid type for getValue: "+b)}return null}
function Fa(a,b){if(0===b||!a)return"";for(var c=0,e,f=0;;){assert(a+f<w);e=A(a+f|0,1,1)|0;c|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,D.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return Ha(a)}var Ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ja(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Ia)return Ia.decode(a.subarray(b,c));for(c="";;){var e=a[b++];if(!e)return c;if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var m=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|m;else{var q=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|m<<6|q;else{var t=a[b++]&63;e=(e&1)<<30|f<<24|g<<18|m<<12|q<<6|t}}}65536>e?c+=String.fromCharCode(e):(e-=
65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}}function Ha(a){return Ja(D,a)}
function Ca(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var m=a.charCodeAt(g);if(55296<=m&&57343>=m){var q=a.charCodeAt(++g);m=65536+((m&1023)<<10)|q&1023}if(127>=m){if(c>=e)break;b[c++]=m}else{if(2047>=m){if(c+1>=e)break;b[c++]=192|m>>6}else{if(65535>=m){if(c+2>=e)break;b[c++]=224|m>>12}else{if(2097151>=m){if(c+3>=e)break;b[c++]=240|m>>18}else{if(67108863>=m){if(c+4>=e)break;b[c++]=248|m>>24}else{if(c+5>=e)break;b[c++]=252|m>>30;b[c++]=128|m>>24&63}b[c++]=128|m>>18&63}b[c++]=
128|m>>12&63}b[c++]=128|m>>6&63}b[c++]=128|m&63}}b[c]=0;return c-f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ka(a){return a.replace(/__Z[\w\d_]+/g,function(a){oa||(oa={});oa["warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling"]||(oa["warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling"]=1,r("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling"));return a===a?a:a+" ["+a+"]"})}
function La(){a:{var a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}d.extraStackTrace&&(a+="\n"+d.extraStackTrace());return Ka(a)}var buffer,z,D,ta,x,E,ya,za;
function Ma(){d.HEAP8=z=new Int8Array(buffer);d.HEAP16=ta=new Int16Array(buffer);d.HEAP32=x=new Int32Array(buffer);d.HEAPU8=D=new Uint8Array(buffer);d.HEAPU16=new Uint16Array(buffer);d.HEAPU32=E=new Uint32Array(buffer);d.HEAPF32=ya=new Float32Array(buffer);d.HEAPF64=za=new Float64Array(buffer)}var Na,v,ma,Oa,Pa,F,Qa,y;Na=v=Oa=Pa=F=Qa=y=0;ma=!1;
function Ra(){34821223==E[(F>>2)-1]&&2310721022==E[(F>>2)-2]||p("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x02135467, but received 0x"+E[(F>>2)-2].toString(16)+" "+E[(F>>2)-1].toString(16));if(1668509029!==x[0])throw"Runtime error: The application has corrupted its heap memory area (address zero)!";}
function Sa(){p("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+w+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ta=d.TOTAL_STACK||5242880,w=d.TOTAL_MEMORY||67108864;w<Ta&&r("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+w+"! (TOTAL_STACK="+Ta+")");
assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");
d.buffer?(buffer=d.buffer,assert(buffer.byteLength===w,"provided buffer should be "+w+" bytes, but it is "+buffer.byteLength)):("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(assert(0===w%65536),d.wasmMemory=new WebAssembly.Memory({initial:w/65536,maximum:w/65536}),buffer=d.wasmMemory.buffer):buffer=new ArrayBuffer(w),assert(buffer.byteLength===w),d.buffer=buffer);Ma();x[0]=1668509029;ta[1]=25459;
if(115!==D[2]||99!==D[3])throw"Runtime error: expected the system to be little-endian!";function Ua(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Rc;"number"===typeof c?void 0===b.U?d.dynCall_v(c):d.dynCall_vi(c,b.U):c(void 0===b.U?null:b.U)}}}var Va=[],Wa=[],Xa=[],Ya=[],Za=[],G=!1;function $a(){var a=d.preRun.shift();Va.unshift(a)}assert(Math.imul&&Math.fround&&Math.clz32&&Math.trunc,"this is a legacy browser, build with LEGACY_VM_SUPPORT");
var ua=Math.abs,xa=Math.ceil,wa=Math.floor,va=Math.min,H=0,I=null,cb=null,db={};function eb(a){for(var b=a;db[a];)a=b+Math.random();return a}
function fb(a){H++;d.monitorRunDependencies&&d.monitorRunDependencies(H);a?(assert(!db[a]),db[a]=1,null===I&&"undefined"!==typeof setInterval&&(I=setInterval(function(){if(Ba)clearInterval(I),I=null;else{var a=!1,c;for(c in db)a||(a=!0,r("still waiting on run dependencies:")),r("dependency: "+c);a&&r("(end of list)")}},1E4))):r("warning: run dependency added without ID")}
function gb(a){H--;d.monitorRunDependencies&&d.monitorRunDependencies(H);a?(assert(db[a]),delete db[a]):r("warning: run dependency removed without ID");0==H&&(null!==I&&(clearInterval(I),I=null),cb&&(a=cb,cb=null,a()))}d.preloadedImages={};d.preloadedAudios={};function hb(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(d.wasmBinary)return new Uint8Array(d.wasmBinary);if(d.readBinary)return d.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(B){p(B)}}function b(){return d.wasmBinary||!ba&&!k||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){q=a.exports;
if(q.memory){a=q.memory;var b=d.buffer;a.byteLength<b.byteLength&&r("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);d.buffer=buffer=a;Ma()}d.asm=q;d.usingWasm=!0;gb("wasm-instantiate")}function e(a){assert(d===B,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");B=null;c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,
m)}).then(a,function(a){r("failed to asynchronously prepare wasm: "+a);p(a)})}if("object"!==typeof WebAssembly)return p("No WebAssembly support found. Build with -s WASM=0 to target JavaScript instead."),r("no native wasm support detected"),!1;if(!(d.wasmMemory instanceof WebAssembly.Memory))return r("no native wasm Memory in use"),!1;a.memory=d.wasmMemory;m.global={NaN:NaN,Infinity:Infinity};m["global.Math"]=Math;m.env=a;fb("wasm-instantiate");if(d.instantiateWasm)try{return d.instantiateWasm(m,
c)}catch(Q){return r("Module.instantiateWasm callback failed with error: "+Q),!1}var B=d;d.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||hb(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),m).then(e,function(a){r("wasm streaming compile failed: "+a);r("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="mdx.wast",f="./js/lib/webMDX/mdx.wasm",g="mdx.temp.asm.js";hb(e)||(e=da(e));hb(f)||(f=da(f));hb(g)||(g=da(g));var m={global:null,
env:null,asm2wasm:qa,parent:d},q=null;d.asmPreload=d.asm;var t=d.reallocBuffer;d.reallocBuffer=function(a){if("asmjs"===C)var b=t(a);else a:{var c=d.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=d.buffer.byteLength;if(d.usingWasm)try{b=-1!==d.wasmMemory.grow((a-c)/65536)?d.buffer=d.wasmMemory.buffer:null;break a}catch(Ga){console.error("Module.reallocBuffer: Attempted to grow from "+c+" bytes to "+a+" bytes, but got error: "+Ga);b=null;break a}b=void 0}return b};var C="";d.asm=function(a,b){if(!b.table){a=
d.wasmTableSize;void 0===a&&(a=1024);var e=d.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);d.wasmTable=b.table}b.memoryBase||(b.memoryBase=d.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: http://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#binaryen-methods");
return b}})();Na=1024;v=Na+205536;Wa.push();d.STATIC_BASE=Na;d.STATIC_BUMP=205536;var ib=v;v+=16;assert(0==ib%8);function ___cxa_free_exception(a){try{return jb(a)}catch(b){r("exception during cxa_free_exception: "+b)}}function kb(){return!!kb.V}var lb=0,mb={};
function nb(){var a=lb;if(!a)return(ka(0),0)|0;var b=mb[a],c=b.type;if(!c)return(ka(0),a)|0;var e=Array.prototype.slice.call(arguments);d.___cxa_is_pointer_type(c);ob||(ob=pb(4));sa(ob|0,a|0,4);a=ob;for(var f=0;f<e.length;f++)if(e[f]&&d.___cxa_can_catch(e[f],c,a))return a=A(a|0,4,0)|0,b.Aa=a,(ka(e[f]),a)|0;a=A(a|0,4,0)|0;return(ka(c),a)|0}
var ob,J={F:1,u:2,Ac:3,wb:4,B:5,ga:6,Pa:7,Ub:8,s:9,cb:10,ba:11,Kc:11,wa:12,P:13,pb:14,fc:15,R:16,da:17,Lc:18,T:19,ea:20,I:21,h:22,Pb:23,va:24,C:25,Hc:26,qb:27,bc:28,M:29,xc:30,Ib:31,qc:32,mb:33,uc:34,Yb:42,tb:43,eb:44,zb:45,Ab:46,Bb:47,Hb:48,Ic:49,Sb:50,yb:51,jb:35,Vb:37,Va:52,Ya:53,Mc:54,Qb:55,Za:56,$a:57,kb:35,ab:59,dc:60,Tb:61,Ec:62,cc:63,Zb:64,$b:65,wc:66,Wb:67,Sa:68,Bc:69,fb:70,rc:71,Kb:72,nb:73,Xa:74,lc:76,Wa:77,vc:78,Cb:79,Db:80,Gb:81,Fb:82,Eb:83,ec:38,fa:39,Lb:36,S:40,mc:95,pc:96,ib:104,Rb:105,
Ta:97,tc:91,jc:88,ac:92,yc:108,hb:111,Qa:98,gb:103,Ob:101,Mb:100,Fc:110,rb:112,sb:113,vb:115,Ua:114,lb:89,Jb:90,sc:93,zc:94,Ra:99,Nb:102,xb:106,hc:107,Gc:109,Jc:87,ob:122,Cc:116,kc:95,Xb:123,ub:84,nc:75,bb:125,ic:131,oc:130,Dc:86},qb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function rb(a){d.___errno_location?sa(d.___errno_location()|0,a|0,4):r("failed to set errno from JS");return a}
function sb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function tb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=sb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ub(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function vb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function wb(){var a=Array.prototype.slice.call(arguments,0);return tb(a.join("/"))}function K(a,b){return tb(a+"/"+b)}
function xb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=sb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var yb=[];function zb(a,b){yb[a]={input:[],output:[],H:b};Ab(a,Bb)}
var Bb={open:function(a){var b=yb[a.node.rdev];if(!b)throw new L(J.T);a.tty=b;a.seekable=!1},close:function(a){a.tty.H.flush(a.tty)},flush:function(a){a.tty.H.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.H.pa)throw new L(J.ga);for(var f=0,g=0;g<e;g++){try{var m=a.tty.H.pa(a.tty)}catch(q){throw new L(J.B);}if(void 0===m&&0===f)throw new L(J.ba);if(null===m||void 0===m)break;f++;b[c+g]=m}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.H.$)throw new L(J.ga);
for(var f=0;f<e;f++)try{a.tty.H.$(a.tty,b[c+f])}catch(g){throw new L(J.B);}e&&(a.node.timestamp=Date.now());return f}},Db={pa:function(a){if(!a.input.length){var b=null;if(l){var c=new Buffer(256),e=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(m){}}try{e=fs.readSync(f,c,0,256,null)}catch(m){if(-1!=m.toString().indexOf("EOF"))e=0;else throw m;}g&&fs.closeSync(f);0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Cb(b)}return a.input.shift()},$:function(a,b){null===b||10===b?(ha(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ha(Ja(a.output,0)),a.output=[])}},Eb={$:function(a,b){null===b||10===b?(r(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&
(r(Ja(a.output,0)),a.output=[])}},M={m:null,j:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,e){if(24576===(c&61440)||4096===(c&61440))throw new L(J.F);M.m||(M.m={dir:{node:{o:M.c.o,i:M.c.i,lookup:M.c.lookup,J:M.c.J,rename:M.c.rename,unlink:M.c.unlink,rmdir:M.c.rmdir,readdir:M.c.readdir,symlink:M.c.symlink},stream:{A:M.f.A}},file:{node:{o:M.c.o,i:M.c.i},stream:{A:M.f.A,read:M.f.read,write:M.f.write,ha:M.f.ha,sa:M.f.sa,ua:M.f.ua}},link:{node:{o:M.c.o,i:M.c.i,readlink:M.c.readlink},
stream:{}},ka:{node:{o:M.c.o,i:M.c.i},stream:Fb}});c=Gb(a,b,c,e);N(c.mode)?(c.c=M.m.dir.node,c.f=M.m.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=M.m.file.node,c.f=M.m.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=M.m.link.node,c.f=M.m.link.stream):8192===(c.mode&61440)&&(c.c=M.m.ka.node,c.f=M.m.ka.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ea:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Sc:function(a){return a.b?a.b.subarray?
a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},la:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=M.Ea(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Ka:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));c&&
a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{o:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.D=4096;b.blocks=Math.ceil(b.size/b.D);return b},
i:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Ka(a,b.size)},lookup:function(){throw Hb[J.u];},J:function(a,b,c,e){return M.createNode(a,b,c,e)},rename:function(a,b,c){if(N(a.mode)){try{var e=Ib(b,c)}catch(g){}if(e)for(var f in e.b)throw new L(J.fa);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Ib(a,b),e;for(e in c.b)throw new L(J.fa);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(J.h);return a.link}},f:{read:function(a,b,c,e,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,e);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write:function(a,b,c,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return assert(0===f,"canOwn must imply no weird position inside the file"),a.b=b.subarray(c,c+e),a.g=e;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+e)),a.g=e;if(f+e<=a.g)return a.b.set(b.subarray(c,c+e),f),e}M.la(a,f+e);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+e);return e},A:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new L(J.h);return b},
ha:function(a,b,c){M.la(a.node,b+c);a.node.g=Math.max(a.node.g,b+c)},sa:function(a,b,c,e,f,g,m){if(32768!==(a.node.mode&61440))throw new L(J.T);c=a.node.b;if(m&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+e<a.node.g)c.subarray?c=c.subarray(f,f+e):c=Array.prototype.slice.call(c,f,f+e);a=!0;e=pb(e);if(!e)throw new L(J.wa);b.set(c,e)}else a=!1,e=c.byteOffset;return{Ja:e,Nc:a}},ua:function(a,b,c,e,f){if(32768!==(a.node.mode&61440))throw new L(J.T);if(f&2)return 0;M.f.write(a,b,0,e,c,!1);return 0}}},
O={O:!1,Na:function(){O.O=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);O.ma={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ia:function(a){return Buffer.V?Buffer.from(a):new Buffer(a)},j:function(a){assert(l);return O.createNode(null,"/",O.oa(a.Z.root),0)},createNode:function(a,b,c){if(!N(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(J.h);a=Gb(a,b,c);a.c=O.c;a.f=O.f;return a},oa:function(a){try{var b=
fs.lstatSync(a);O.O&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}return b.mode},l:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.j.Z.root);b.reverse();return wb.apply(null,b)},Da:function(a){a&=-2656257;var b=0,c;for(c in O.ma)a&c&&(b|=O.ma[c],a^=c);if(a)throw new L(J.h);return b},c:{o:function(a){a=O.l(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}O.O&&!b.D&&(b.D=4096);O.O&&!b.blocks&&(b.blocks=
(b.size+b.D-1)/b.D|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,D:b.D,blocks:b.blocks}},i:function(a,b){var c=O.l(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(e){if(!e.code)throw e;throw new L(J[e.code]);}},lookup:function(a,b){var c=K(O.l(a),b);c=O.oa(c);return O.createNode(a,b,c)},J:function(a,b,c,e){a=O.createNode(a,b,c,e);b=O.l(a);
try{N(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new L(J[f.code]);}return a},rename:function(a,b,c){a=O.l(a);b=K(O.l(b),c);try{fs.renameSync(a,b)}catch(e){if(!e.code)throw e;throw new L(J[e.code]);}},unlink:function(a,b){a=K(O.l(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},rmdir:function(a,b){a=K(O.l(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},readdir:function(a){a=O.l(a);
try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(J[b.code]);}},symlink:function(a,b,c){a=K(O.l(a),b);try{fs.symlinkSync(c,a)}catch(e){if(!e.code)throw e;throw new L(J[e.code]);}},readlink:function(a){var b=O.l(a);try{return b=fs.readlinkSync(b),b=Jb.relative(Jb.resolve(a.j.Z.root),b)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}}},f:{open:function(a){var b=O.l(a.node);try{32768===(a.node.mode&61440)&&(a.L=fs.openSync(b,O.Da(a.flags)))}catch(c){if(!c.code)throw c;throw new L(J[c.code]);
}},close:function(a){try{32768===(a.node.mode&61440)&&a.L&&fs.closeSync(a.L)}catch(b){if(!b.code)throw b;throw new L(J[b.code]);}},read:function(a,b,c,e,f){if(0===e)return 0;try{return fs.readSync(a.L,O.ia(b.buffer),c,e,f)}catch(g){throw new L(J[g.code]);}},write:function(a,b,c,e,f){try{return fs.writeSync(a.L,O.ia(b.buffer),c,e,f)}catch(g){throw new L(J[g.code]);}},A:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.L).size}catch(e){throw new L(J[e.code]);
}if(0>b)throw new L(J.h);return b}}};v+=16;v+=16;v+=16;var Kb=null,Lb={},Mb=[],Nb=1,P=null,Ob=!0,R={},L=null,Hb={};
function S(a,b){a=xb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={na:!0,aa:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.aa)throw new L(J.S);a=sb(a.split("/").filter(function(a){return!!a}),!1);var f=Kb;c="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=Ib(f,a[e]);c=K(c,a[e]);f.K&&(!g||g&&b.na)&&(f=f.K.root);if(!g||b.W)for(g=0;40960===(f.mode&61440);)if(f=Pb(c),c=xb(ub(c),f),f=S(c,{aa:b.aa}).node,40<g++)throw new L(J.S);}return{path:c,node:f}}
function T(a){for(var b;;){if(a===a.parent)return a=a.j.ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Qb(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%P.length}function Rb(a){var b=Qb(a.parent.id,a.name);a.G=P[b];P[b]=a}function Ib(a,b){var c;if(c=(c=Sb(a,"x"))?c:a.c.lookup?0:J.P)throw new L(c,a);for(c=P[Qb(a.id,b)];c;c=c.G){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return a.c.lookup(a,b)}
function Gb(a,b,c,e){Tb||(Tb=function(a,b,c,e){a||(a=this);this.parent=a;this.j=a.j;this.K=null;this.id=Nb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=e},Tb.prototype={},Object.defineProperties(Tb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ha:{get:function(){return N(this.mode)}},Ga:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Tb(a,b,c,e);Rb(a);return a}function N(a){return 16384===(a&61440)}var Ub={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Vb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Sb(a,b){if(Ob)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return J.P}else return J.P;return 0}
function Wb(a,b){try{return Ib(a,b),J.da}catch(c){}return Sb(a,"wx")}function Xb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Mb[a])return a;throw new L(J.va);}function Yb(a,b){Zb||(Zb=function(){},Zb.prototype={},Object.defineProperties(Zb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Zb,e;for(e in a)c[e]=a[e];a=c;b=Xb(b);a.fd=b;return Mb[b]=a}var Fb={open:function(a){a.f=Lb[a.node.rdev].f;a.f.open&&a.f.open(a)},A:function(){throw new L(J.M);}};
function Ab(a,b){Lb[a]={f:b}}function $b(a,b){var c="/"===b,e=!b;if(c&&Kb)throw new L(J.R);if(!c&&!e){var f=S(b,{na:!1});b=f.path;f=f.node;if(f.K)throw new L(J.R);if(!N(f.mode))throw new L(J.ea);}b={type:a,Z:{},ta:b,Ia:[]};a=a.j(b);a.j=b;b.root=a;c?Kb=a:f&&(f.K=b,f.j&&f.j.Ia.push(b))}function ac(a,b,c){var e=S(a,{parent:!0}).node;a=vb(a);if(!a||"."===a||".."===a)throw new L(J.h);var f=Wb(e,a);if(f)throw new L(f);if(!e.c.J)throw new L(J.F);return e.c.J(e,a,b,c)}
function U(a,b){return ac(a,(void 0!==b?b:511)&1023|16384,0)}function bc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return ac(a,b|8192,c)}function cc(a,b){if(!xb(a))throw new L(J.u);var c=S(b,{parent:!0}).node;if(!c)throw new L(J.u);b=vb(b);var e=Wb(c,b);if(e)throw new L(e);if(!c.c.symlink)throw new L(J.F);return c.c.symlink(c,b,a)}
function dc(a){var b=S(a,{parent:!0}).node,c=vb(a),e=Ib(b,c);a:{try{var f=Ib(b,c)}catch(m){f=m.v;break a}var g=Sb(b,"wx");f=g?g:N(f.mode)?J.I:0}if(f)throw new L(f);if(!b.c.unlink)throw new L(J.F);if(e.K)throw new L(J.R);try{R.willDeletePath&&R.willDeletePath(a)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+m.message)}b.c.unlink(b,c);b=Qb(e.parent.id,e.name);if(P[b]===e)P[b]=e.G;else for(b=P[b];b;){if(b.G===e){b.G=e.G;break}b=b.G}try{if(R.onDeletePath)R.onDeletePath(a)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+m.message)}}function Pb(a){a=S(a).node;if(!a)throw new L(J.u);if(!a.c.readlink)throw new L(J.h);return xb(T(a.parent),a.c.readlink(a))}function ec(a,b){var c;"string"===typeof a?c=S(a,{W:!0}).node:c=a;if(!c.c.i)throw new L(J.F);c.c.i(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function fc(a,b,c,e){if(""===a)throw new L(J.u);if("string"===typeof b){var f=Ub[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=tb(a);try{g=S(a,{W:!(b&131072)}).node}catch(t){}}f=!1;if(b&64)if(g){if(b&128)throw new L(J.da);}else g=ac(a,c,0),f=!0;if(!g)throw new L(J.u);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!N(g.mode))throw new L(J.ea);if(!f){var m=g?40960===(g.mode&61440)?J.S:
N(g.mode)&&("r"!==Vb(b)||b&512)?J.I:Sb(g,Vb(b)):J.u;if(m)throw new L(m);}if(b&512){c=g;var q;"string"===typeof c?q=S(c,{W:!0}).node:q=c;if(!q.c.i)throw new L(J.F);if(N(q.mode))throw new L(J.I);if(32768!==(q.mode&61440))throw new L(J.h);if(c=Sb(q,"w"))throw new L(c);q.c.i(q,{size:0,timestamp:Date.now()})}b&=-641;e=Yb({node:g,path:T(g),flags:b,seekable:!0,position:0,f:g.f,Oa:[],error:!1},e);e.f.open&&e.f.open(e);!d.logReadFiles||b&1||(hc||(hc={}),a in hc||(hc[a]=1,m("read file: "+a)));try{R.onOpenFile&&
(m=0,1!==(b&2097155)&&(m|=1),0!==(b&2097155)&&(m|=2),R.onOpenFile(a,m))}catch(t){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+t.message)}return e}function ic(a){if(null===a.fd)throw new L(J.s);a.X&&(a.X=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Mb[a.fd]=null}a.fd=null}function jc(a,b,c){if(null===a.fd)throw new L(J.s);if(!a.seekable||!a.f.A)throw new L(J.M);a.position=a.f.A(a,b,c);a.Oa=[]}
function kc(a,b,c,e,f,g){if(0>e||0>f)throw new L(J.h);if(null===a.fd)throw new L(J.s);if(0===(a.flags&2097155))throw new L(J.s);if(N(a.node.mode))throw new L(J.I);if(!a.f.write)throw new L(J.h);a.flags&1024&&jc(a,0,2);var m="undefined"!==typeof f;if(!m)f=a.position;else if(!a.seekable)throw new L(J.M);b=a.f.write(a,b,c,e,f,g);m||(a.position+=b);try{if(a.path&&R.onWriteToFile)R.onWriteToFile(a.path)}catch(q){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+q.message)}return b}
function lc(){L||(L=function(a,b){this.node=b;this.Ma=function(a){this.v=a;for(var b in J)if(J[b]===a){this.code=b;break}};this.Ma(a);this.message=qb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0});this.stack&&(this.stack=Ka(this.stack))},L.prototype=Error(),L.prototype.constructor=L,[J.u].forEach(function(a){Hb[a]=new L(a);Hb[a].stack="<generic error, no stack>"}))}var mc;function nc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function oc(a,b,c,e){a=K("string"===typeof a?a:T(a),b);return U(a,nc(c,e))}function pc(a,b){a="string"===typeof a?a:T(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=K(a,c);try{U(e)}catch(f){}a=e}}return e}function qc(a,b,c,e){a=K("string"===typeof a?a:T(a),b);c=nc(c,e);return ac(a,(void 0!==c?c:438)&4095|32768,0)}
function rc(a,b,c,e,f,g){a=b?K("string"===typeof a?a:T(a),b):a;e=nc(e,f);f=ac(a,(void 0!==e?e:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var m=c.length;b<m;++b)a[b]=c.charCodeAt(b);c=a}ec(f,e|146);a=fc(f,"w");kc(a,c,0,c.length,0,g);ic(a);ec(f,e)}return f}
function V(a,b,c,e){a=K("string"===typeof a?a:T(a),b);b=nc(!!c,!!e);V.ra||(V.ra=64);var f=V.ra++<<8|0;Ab(f,{open:function(a){a.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(a,b,e,f){for(var g=0,m=0;m<f;m++){try{var q=c()}catch(Z){throw new L(J.B);}if(void 0===q&&0===g)throw new L(J.ba);if(null===q||void 0===q)break;g++;b[e+m]=q}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{e(b[c+g])}catch(B){throw new L(J.B);}f&&(a.node.timestamp=
Date.now());return g}});return bc(a,b,f)}function sc(a,b,c){a=K("string"===typeof a?a:T(a),b);return cc(c,a)}
function tc(a){if(a.Ga||a.Ha||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(d.read)try{a.b=Cb(d.read(a.url)),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||rb(J.B);return b}
function uc(a,b,c,e,f){function g(){this.Y=!1;this.N=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.qa(a/this.chunkSize|0)[b]}};g.prototype.La=function(a){this.qa=a};g.prototype.ja=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),e,f=(e=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
e;a=(e=a.getResponseHeader("Content-Encoding"))&&"gzip"===e;var g=1048576;f||(g=b);var m=this;m.La(function(a){var e=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof m.N[a]){var q=m.N;if(e>f)throw Error("invalid range ("+e+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var t=new XMLHttpRequest;t.open("GET",c,!1);b!==g&&t.setRequestHeader("Range","bytes="+e+"-"+f);"undefined"!=typeof Uint8Array&&(t.responseType="arraybuffer");t.overrideMimeType&&
t.overrideMimeType("text/plain; charset=x-user-defined");t.send(null);if(!(200<=t.status&&300>t.status||304===t.status))throw Error("Couldn't load "+c+". Status: "+t.status);e=void 0!==t.response?new Uint8Array(t.response||[]):Cb(t.responseText||"");q[a]=e}if("undefined"===typeof m.N[a])throw Error("doXHR failed!");return m.N[a]});if(a||!b)g=b=1,g=b=this.qa(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.za=b;this.ya=g;this.Y=!0};if("undefined"!==
typeof XMLHttpRequest){if(!k)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var m=new g;Object.defineProperties(m,{length:{get:function(){this.Y||this.ja();return this.za}},chunkSize:{get:function(){this.Y||this.ja();return this.ya}}});var q=void 0}else q=c,m=void 0;var t=qc(a,b,e,f);m?t.b=m:q&&(t.b=null,t.url=q);Object.defineProperties(t,{g:{get:function(){return this.b.length}}});var C={};Object.keys(t.f).forEach(function(a){var b=
t.f[a];C[a]=function(){if(!tc(t))throw new L(J.B);return b.apply(null,arguments)}});C.read=function(a,b,c,e,f){if(!tc(t))throw new L(J.B);a=a.node.b;if(f>=a.length)return 0;e=Math.min(a.length-f,e);assert(0<=e);if(a.slice)for(var g=0;g<e;g++)b[c+g]=a[f+g];else for(g=0;g<e;g++)b[c+g]=a.get(f+g);return e};t.f=C;return t}
function vc(a,b,c,e,f,g,m,q,t,C){function B(c){function B(c){C&&C();q||rc(a,b,c,e,f,t);g&&g();gb(Z)}var Q=!1;d.preloadPlugins.forEach(function(a){!Q&&a.canHandle(pa)&&(a.handle(c,pa,B,function(){m&&m();gb(Z)}),Q=!0)});Q||B(c)}Browser.Tc();var pa=b?xb(K(a,b)):a,Z=eb("cp "+pa);fb(Z);"string"==typeof c?Browser.Oc(c,function(a){B(a)},m):B(c)}var FS={},Tb,Zb,hc,W=0;function X(){W+=4;return A(W-4|0,4,0)|0}function wc(){var a=Mb[X()];if(!a)throw new L(J.s);return a}function xc(a){return Math.pow(2,a)}lc();
P=Array(4096);$b(M,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");Ab(259,{read:function(){return 0},write:function(a,b,f,g){return g}});bc("/dev/null",259);zb(1280,Db);zb(1536,Eb);bc("/dev/tty",1280);bc("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else l?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){p("random_device")};V("/dev","random",b);V("/dev","urandom",b);U("/dev/shm");U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");
$b({j:function(){var a=Gb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=Mb[+c];if(!b)throw new L(J.s);a={parent:null,j:{ta:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Wa.unshift(function(){if(!d.noFSInit&&!mc){assert(!mc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");mc=!0;lc();d.stdin=d.stdin;d.stdout=d.stdout;d.stderr=d.stderr;d.stdin?V("/dev","stdin",d.stdin):cc("/dev/tty","/dev/stdin");d.stdout?V("/dev","stdout",null,d.stdout):cc("/dev/tty","/dev/stdout");d.stderr?V("/dev","stderr",null,d.stderr):cc("/dev/tty1","/dev/stderr");var a=
fc("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=fc("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=fc("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Xa.push(function(){Ob=!1});Ya.push(function(){mc=!1;var a=d._fflush;a&&a(0);for(a=0;a<Mb.length;a++){var b=Mb[a];b&&ic(b)}});d.FS_createFolder=oc;d.FS_createPath=pc;d.FS_createDataFile=rc;d.FS_createPreloadedFile=vc;d.FS_createLazyFile=uc;d.FS_createLink=sc;
d.FS_createDevice=V;d.FS_unlink=dc;Wa.unshift(function(){});Ya.push(function(){});if(l){var fs=require("fs"),Jb=require("path");O.Na()}y=la(4);Oa=Pa=na(v);F=Oa+Ta;Qa=na(F);x[y>>2]=Qa;ma=!0;assert(Qa<w,"TOTAL_MEMORY not big enough for stack");
function Cb(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}b=Array(b+1);a=Ca(a,b,0,b.length);b.length=a;return b}d.wasmTableSize=68;d.wasmMaxTableSize=68;d.Ba={};
d.Ca={enlargeMemory:function(){Sa()},getTotalMemory:function(){return w},abortOnCannotGrowMemory:Sa,abortStackOverflow:function(a){p("Stack overflow! Attempted to allocate "+a+" bytes on the stack, but stack has only "+(F-u()+a)+" bytes available!")},segfault:function(){p("segmentation fault")},alignfault:function(){p("alignment fault")},nullFunc_ii:function(a){r("Invalid function pointer called with signature 'ii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_iiii:function(a){r("Invalid function pointer called with signature 'iiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_v:function(a){r("Invalid function pointer called with signature 'v'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_vi:function(a){r("Invalid function pointer called with signature 'vi'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_vii:function(a){r("Invalid function pointer called with signature 'vii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_viii:function(a){r("Invalid function pointer called with signature 'viii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_viiii:function(a){r("Invalid function pointer called with signature 'viiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_viiiii:function(a){r("Invalid function pointer called with signature 'viiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");r("Build with ASSERTIONS=2 for more info.");p(a)},nullFunc_viiiiii:function(a){r("Invalid function pointer called with signature 'viiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
r("Build with ASSERTIONS=2 for more info.");p(a)},invoke_ii:function(a,b){var c=u();try{return d.dynCall_ii(a,b)}catch(e){ia(c);if("number"!==typeof e&&"longjmp"!==e)throw e;d.setThrew(1,0)}},invoke_vi:function(a,b){var c=u();try{d.dynCall_vi(a,b)}catch(e){ia(c);if("number"!==typeof e&&"longjmp"!==e)throw e;d.setThrew(1,0)}},invoke_viii:function(a,b,c,e){var f=u();try{d.dynCall_viii(a,b,c,e)}catch(g){ia(f);if("number"!==typeof g&&"longjmp"!==g)throw g;d.setThrew(1,0)}},___assert_fail:function(a,b,
c,e){p("Assertion failed: "+Fa(a)+", at: "+[b?Fa(b):"unknown filename",c,e?Fa(e):"unknown function"])},___cxa_allocate_exception:function(a){return pb(a)},___cxa_find_matching_catch_2:function(){return nb.apply(null,arguments)},___cxa_free_exception:___cxa_free_exception,___cxa_pure_virtual:function(){Ba=!0;throw"Pure virtual function called!";},___cxa_throw:function(a,b,c){mb[a]={Ja:a,Aa:a,type:b,Qc:c,Uc:0,Pc:!1,Vc:!1};lb=a;"uncaught_exception"in kb?kb.V++:kb.V=1;throw a;},___lock:function(){},___resumeException:function(a){lb||
(lb=a);throw a;},___setErrNo:rb,___syscall140:function(a,b){W=b;try{var c=wc();X();var e=X(),f=X(),g=X();jc(c,e,g);sa(f|0,c.position|0,4);c.X&&0===e&&0===g&&(c.X=null);return 0}catch(m){return"undefined"!==typeof FS&&m instanceof L||p(m),-m.v}},___syscall145:function(a,b){W=b;try{var c=wc(),e=X();a:{var f=X();for(b=a=0;b<f;b++){var g=A(e+8*b|0,4,0)|0,m=A(e+(8*b+4)|0,4,0)|0,q=c,t=g,C=m,B=void 0,pa=z;if(0>C||0>B)throw new L(J.h);if(null===q.fd)throw new L(J.s);if(1===(q.flags&2097155))throw new L(J.s);
if(N(q.node.mode))throw new L(J.I);if(!q.f.read)throw new L(J.h);var Z="undefined"!==typeof B;if(!Z)B=q.position;else if(!q.seekable)throw new L(J.M);var Ga=q.f.read(q,pa,t,C,B);Z||(q.position+=Ga);var bb=Ga;if(0>bb){var Q=-1;break a}a+=bb;if(bb<m)break}Q=a}return Q}catch(ab){return"undefined"!==typeof FS&&ab instanceof L||p(ab),-ab.v}},___syscall146:function(a,b){W=b;try{var c=wc(),e=X();a:{var f=X();for(b=a=0;b<f;b++){var g=A(e+8*b|0,4,0)|0,m=A(e+(8*b+4)|0,4,0)|0,q=kc(c,z,g,m,void 0);if(0>q){var t=
-1;break a}a+=q}t=a}return t}catch(C){return"undefined"!==typeof FS&&C instanceof L||p(C),-C.v}},___syscall221:function(a,b){W=b;try{var c=wc();switch(X()){case 0:var e=X();return 0>e?-J.h:fc(c.path,c.flags,0,e).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return e=X(),c.flags|=e,0;case 12:case 12:return e=X(),sa(e+0|0,2,2),0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-J.h;case 9:return rb(J.h),-1;default:return-J.h}}catch(f){return"undefined"!==typeof FS&&f instanceof
L||p(f),-f.v}},___syscall5:function(a,b){W=b;try{var c=Fa(X()),e=X(),f=X();return fc(c,e,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof L||p(g),-g.v}},___syscall54:function(a,b){W=b;try{var c=wc(),e=X();switch(e){case 21509:case 21505:return c.tty?0:-J.C;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-J.C;case 21519:if(!c.tty)return-J.C;var f=X();sa(f|0,0,4);return 0;case 21520:return c.tty?-J.h:-J.C;case 21531:a=f=X();if(!c.f.Fa)throw new L(J.C);return c.f.Fa(c,
e,a);case 21523:return c.tty?0:-J.C;case 21524:return c.tty?0:-J.C;default:p("bad ioctl syscall "+e)}}catch(g){return"undefined"!==typeof FS&&g instanceof L||p(g),-g.v}},___syscall6:function(a,b){W=b;try{var c=wc();ic(c);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof L||p(e),-e.v}},___unlock:function(){},_ems_request_file:function(a){var b=window.ScriptNodePlayer.getInstance();if(b.isReady())return b._fileRequestCallback(a);window.console.log("error: ems_request_file not ready")},_emscripten_memcpy_big:function(a,
b,c){D.set(D.subarray(b,b+c),a);return a},_llvm_exp2_f64:function(){return xc.apply(null,arguments)},DYNAMICTOP_PTR:y,STACKTOP:Pa,STACK_MAX:F};var Y=d.asm(d.Ba,d.Ca,buffer),yc=Y.___errno_location;Y.___errno_location=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return yc.apply(null,arguments)};var zc=Y._emu_compute_audio_samples;
Y._emu_compute_audio_samples=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return zc.apply(null,arguments)};var Ac=Y._emu_get_audio_buffer;
Y._emu_get_audio_buffer=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ac.apply(null,arguments)};var Bc=Y._emu_get_audio_buffer_length;
Y._emu_get_audio_buffer_length=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Bc.apply(null,arguments)};var Cc=Y._emu_get_current_position;
Y._emu_get_current_position=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Cc.apply(null,arguments)};var Dc=Y._emu_get_max_position;
Y._emu_get_max_position=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Dc.apply(null,arguments)};var Ec=Y._emu_get_sample_rate;
Y._emu_get_sample_rate=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ec.apply(null,arguments)};var Fc=Y._emu_get_track_info;
Y._emu_get_track_info=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Fc.apply(null,arguments)};var Gc=Y._emu_load_file;
Y._emu_load_file=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Gc.apply(null,arguments)};var Hc=Y._emu_seek_position;
Y._emu_seek_position=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Hc.apply(null,arguments)};var Ic=Y._emu_set_subsong;
Y._emu_set_subsong=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ic.apply(null,arguments)};var Jc=Y._emu_teardown;
Y._emu_teardown=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Jc.apply(null,arguments)};var Kc=Y._fflush;Y._fflush=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Kc.apply(null,arguments)};
var Lc=Y._free;Y._free=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Lc.apply(null,arguments)};var Mc=Y._llvm_bswap_i32;
Y._llvm_bswap_i32=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Mc.apply(null,arguments)};var Nc=Y._malloc;Y._malloc=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Nc.apply(null,arguments)};
var Oc=Y._sbrk;Y._sbrk=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Oc.apply(null,arguments)};var Pc=Y.establishStackSpace;
Y.establishStackSpace=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Pc.apply(null,arguments)};var Qc=Y.getTempRet0;
Y.getTempRet0=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Qc.apply(null,arguments)};var Rc=Y.setDynamicTop;
Y.setDynamicTop=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Rc.apply(null,arguments)};var Sc=Y.setTempRet0;
Y.setTempRet0=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Sc.apply(null,arguments)};var Tc=Y.setThrew;Y.setThrew=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Tc.apply(null,arguments)};
var Uc=Y.stackAlloc;Y.stackAlloc=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Uc.apply(null,arguments)};var Vc=Y.stackRestore;
Y.stackRestore=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Vc.apply(null,arguments)};var Wc=Y.stackSave;Y.stackSave=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Wc.apply(null,arguments)};
d.asm=Y;d.___errno_location=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.___errno_location.apply(null,arguments)};
d._emu_compute_audio_samples=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_compute_audio_samples.apply(null,arguments)};
d._emu_get_audio_buffer=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_get_audio_buffer.apply(null,arguments)};
d._emu_get_audio_buffer_length=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_get_audio_buffer_length.apply(null,arguments)};
d._emu_get_current_position=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_get_current_position.apply(null,arguments)};
d._emu_get_max_position=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_get_max_position.apply(null,arguments)};
d._emu_get_sample_rate=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_get_sample_rate.apply(null,arguments)};
d._emu_get_track_info=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_get_track_info.apply(null,arguments)};
d._emu_load_file=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_load_file.apply(null,arguments)};
d._emu_seek_position=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_seek_position.apply(null,arguments)};
d._emu_set_subsong=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_set_subsong.apply(null,arguments)};
d._emu_teardown=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._emu_teardown.apply(null,arguments)};
d._fflush=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._fflush.apply(null,arguments)};var jb=d._free=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._free.apply(null,arguments)};
d._llvm_bswap_i32=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._llvm_bswap_i32.apply(null,arguments)};
var pb=d._malloc=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._malloc.apply(null,arguments)};d._sbrk=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm._sbrk.apply(null,arguments)};
d.establishStackSpace=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.establishStackSpace.apply(null,arguments)};
d.getTempRet0=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.getTempRet0.apply(null,arguments)};
d.setDynamicTop=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.setDynamicTop.apply(null,arguments)};
var ka=d.setTempRet0=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.setTempRet0.apply(null,arguments)};
d.setThrew=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.setThrew.apply(null,arguments)};
var ja=d.stackAlloc=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.stackAlloc.apply(null,arguments)},ia=d.stackRestore=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.stackRestore.apply(null,
arguments)},u=d.stackSave=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.stackSave.apply(null,arguments)};
d.dynCall_ii=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.dynCall_ii.apply(null,arguments)};
d.dynCall_v=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.dynCall_v.apply(null,arguments)};
d.dynCall_vi=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.dynCall_vi.apply(null,arguments)};
d.dynCall_viii=function(){assert(G,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!0,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return d.asm.dynCall_viii.apply(null,arguments)};d.asm=Y;d.intArrayFromString||(d.intArrayFromString=function(){p("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.intArrayToString||(d.intArrayToString=function(){p("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.ccall=function(a,b,c,e){var f=d["_"+a];assert(f,"Cannot call unknown function "+a+", make sure it is exported");var g=[];a=0;assert("array"!==b,'Return type should not be "array".');if(e)for(var m=0;m<e.length;m++){var q=Ea[c[m]];q?(0===a&&(a=u()),g[m]=q(e[m])):g[m]=e[m]}c=f.apply(null,g);c="string"===b?Fa(c):"boolean"===b?!!c:c;0!==a&&ia(a);return c};d.cwrap||(d.cwrap=function(){p("'cwrap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.setValue||(d.setValue=function(){p("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.getValue||(d.getValue=function(){p("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.allocate||(d.allocate=function(){p("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.getMemory=function(a){if(ma)if(G)var b=pb(a);else{assert(y);b=x[y>>2];a=b+a+15&-16;x[y>>2]=a;if(a=a>=w)Sa(),a=!0;a&&(x[y>>2]=b,b=0)}else b=la(a);return b};d.Pointer_stringify=Fa;d.AsciiToString||(d.AsciiToString=function(){p("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.stringToAscii||(d.stringToAscii=function(){p("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.UTF8ArrayToString||(d.UTF8ArrayToString=function(){p("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.UTF8ToString=Ha;d.stringToUTF8Array||(d.stringToUTF8Array=function(){p("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.stringToUTF8||(d.stringToUTF8=function(){p("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.lengthBytesUTF8||(d.lengthBytesUTF8=function(){p("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.UTF16ToString||(d.UTF16ToString=function(){p("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.stringToUTF16||(d.stringToUTF16=function(){p("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.lengthBytesUTF16||(d.lengthBytesUTF16=function(){p("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.UTF32ToString||(d.UTF32ToString=function(){p("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.stringToUTF32||(d.stringToUTF32=function(){p("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.lengthBytesUTF32||(d.lengthBytesUTF32=function(){p("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.allocateUTF8||(d.allocateUTF8=function(){p("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.stackTrace||(d.stackTrace=function(){p("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.addOnPreRun||(d.addOnPreRun=function(){p("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.addOnInit||(d.addOnInit=function(){p("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.addOnPreMain||(d.addOnPreMain=function(){p("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.addOnExit||(d.addOnExit=function(){p("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.addOnPostRun||(d.addOnPostRun=function(){p("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.writeStringToMemory||(d.writeStringToMemory=function(){p("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.writeArrayToMemory||(d.writeArrayToMemory=function(){p("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.writeAsciiToMemory||(d.writeAsciiToMemory=function(){p("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.addRunDependency=fb;d.removeRunDependency=gb;d.ENV||(d.ENV=function(){p("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.FS||(d.FS=function(){p("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.FS_createFolder=oc;d.FS_createPath=pc;d.FS_createDataFile=rc;
d.FS_createPreloadedFile=vc;d.FS_createLazyFile=uc;d.FS_createLink=sc;d.FS_createDevice=V;d.FS_unlink=dc;d.GL||(d.GL=function(){p("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.staticAlloc||(d.staticAlloc=function(){p("'staticAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.dynamicAlloc||(d.dynamicAlloc=function(){p("'dynamicAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.warnOnce||(d.warnOnce=function(){p("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.loadDynamicLibrary||(d.loadDynamicLibrary=function(){p("'loadDynamicLibrary' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.loadWebAssemblyModule||(d.loadWebAssemblyModule=function(){p("'loadWebAssemblyModule' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.getLEB||(d.getLEB=function(){p("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.getFunctionTables||(d.getFunctionTables=function(){p("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.alignFunctionTables||(d.alignFunctionTables=function(){p("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.registerFunctions||(d.registerFunctions=function(){p("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.addFunction||(d.addFunction=function(){p("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.removeFunction||(d.removeFunction=function(){p("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.getFuncWrapper||(d.getFuncWrapper=function(){p("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.prettyPrint||(d.prettyPrint=function(){p("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.makeBigInt||(d.makeBigInt=function(){p("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.dynCall||(d.dynCall=function(){p("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.getCompilerSetting||(d.getCompilerSetting=function(){p("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.stackSave||(d.stackSave=function(){p("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.stackRestore||(d.stackRestore=function(){p("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.stackAlloc||(d.stackAlloc=function(){p("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.establishStackSpace||(d.establishStackSpace=function(){p("'establishStackSpace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.print||(d.print=function(){p("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});d.printErr||(d.printErr=function(){p("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
d.ALLOC_NORMAL||Object.defineProperty(d,"ALLOC_NORMAL",{get:function(){p("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});d.ALLOC_STACK||Object.defineProperty(d,"ALLOC_STACK",{get:function(){p("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});d.ALLOC_STATIC||Object.defineProperty(d,"ALLOC_STATIC",{get:function(){p("'ALLOC_STATIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
d.ALLOC_DYNAMIC||Object.defineProperty(d,"ALLOC_DYNAMIC",{get:function(){p("'ALLOC_DYNAMIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});d.ALLOC_NONE||Object.defineProperty(d,"ALLOC_NONE",{get:function(){p("'ALLOC_NONE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});cb=function Xc(){d.calledRun||Yc();d.calledRun||(cb=Xc)};
function Yc(){function a(){if(!d.calledRun&&(d.calledRun=!0,!Ba)){Ra();G||(G=!0,Ua(Wa));Ra();Ua(Xa);if(d.onRuntimeInitialized)d.onRuntimeInitialized();assert(!d._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');Ra();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var a=d.postRun.shift();Za.unshift(a)}Ua(Za)}}if(!(0<H)){assert(0==(F&3));E[(F>>2)-1]=34821223;E[(F>>2)-2]=2310721022;if(d.preRun)for("function"==
typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)$a();Ua(Va);0<H||d.calledRun||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a(),Ra())}}d.run=Yc;var Zc=[];function p(a){if(d.onAbort)d.onAbort(a);void 0!==a?(ha(a),r(a),a=JSON.stringify(a)):a="";Ba=!0;var b="abort("+a+") at "+La()+"";Zc&&Zc.forEach(function(c){b=c(b,a)});throw b;}d.abort=p;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();
d.noExitRuntime=!0;Yc();
  return {
	Module: Module,  // expose original Module
  };
})(window.spp_backend_state_mdx);
/*
 mdx_adapter.js: Adapts MDX/PMD backend to generic WebAudio/ScriptProcessor player.

 version 1.1

 	Copyright (C) 2023 Juergen Wothke


 note: requires SrciptNodePlayer version >= 1.2.1


 LICENSE

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2.1 of the License, or (at
 your option) any later version. This library is distributed in the hope
 that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
*/
class MDXBackendAdapter extends EmsHEAP16BackendAdapter {
	constructor()
	{
		super(backend_mdx.Module, 2, new SimpleFileMapper(backend_mdx.Module));

		this.ensureReadyNotification();
	}

	loadMusicData(sampleRate, path, filename, data, options)
	{
		filename = this._getFilename(path, filename);

		let ret = this._loadMusicDataBuffer(filename, data, ScriptNodePlayer.getWebAudioSampleRate(), 1024, false);

		if (ret == 0)
		{
			this._setupOutputResampling(sampleRate);
		}
		return ret;
	}

	getSongInfoMeta()
	{
		return {
			title: String,
			artist: String,
		};
	}

	updateSongInfo(filename)
	{
		let result = this._songInfo;
		
		let numAttr = 2;
		let ret = this.Module.ccall('emu_get_track_info', 'number');
		let array = this.Module.HEAP32.subarray(ret>>2, (ret>>2)+numAttr);

		result.title = this._decodeBinaryToText(array[0], "Shift_JIS", 256);	// according to MDX spec
		result.artist = this._decodeBinaryToText(array[1], "Shift_JIS", 256);
	}
};
