const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Camera3D,
		C3.Plugins.Timeline,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.RemoveAllDynamicLayers,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.ScriptsInEvents.Parentspacekey_Event1,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Acts.SetHeight,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Camera3D.Exps.LookZ
	];
};
self.C3_JsPropNameTable = [
	{biilBoard_score: 0},
	{billboard_montain: 0},
	{billboard_sky: 0},
	{Sine: 0},
	{Sine2: 0},
	{billboard_sun: 0},
	{SkyBoxBottom: 0},
	{SkyBoxSide: 0},
	{SkyBoxTop: 0},
	{Tween: 0},
	{bulle: 0},
	{lookat: 0},
	{map_map: 0},
	{map_mountain: 0},
	{map_sun: 0},
	{num: 0},
	{type: 0},
	{spot: 0},
	{star: 0},
	{spot_img: 0},
	{LevelName: 0},
	{gauge: 0},
	{gaugeBack: 0},
	{level: 0},
	{Flash: 0},
	{gaugePart: 0},
	{TextTotalScore: 0},
	{btnSave: 0},
	{intro_: 0},
	{intro_back: 0},
	{intro_cloud: 0},
	{intro_hawks: 0},
	{intro_pony: 0},
	{intro_proSkater: 0},
	{intro_splash: 0},
	{PlanDeTravail: 0},
	{Clignotement: 0},
	{playNow: 0},
	{pony: 0},
	{btnFullscreen: 0},
	{btnWho: 0},
	{btnMusic: 0},
	{annim_banana: 0},
	{push2begin: 0},
	{PlanDeTravail6: 0},
	{score: 0},
	{score_shadow: 0},
	{tricks: 0},
	{Fade: 0},
	{flash: 0},
	{photoShoot: 0},
	{btnNext: 0},
	{btnRepeat: 0},
	{photo: 0},
	{PlanDeTravail5: 0},
	{push: 0},
	{options: 0},
	{flecheD: 0},
	{flecheG: 0},
	{mag_1: 0},
	{mag_2: 0},
	{mag_3D_1: 0},
	{mag_3D_2: 0},
	{movingPage: 0},
	{movingPage1: 0},
	{movingPage2: 0},
	{btnClose: 0},
	{inspirated_image: 0},
	{introScinematic_1: 0},
	{introScinematic_2: 0},
	{story: 0},
	{keyboard: 0},
	{tricksPos: 0},
	{AJAX: 0},
	{Caméra3D: 0},
	{ContrôleurDeLaTimeline: 0},
	{PlanDeTravail4: 0},
	{wasClicked: 0},
	{tween: 0},
	{Timer: 0},
	{pic: 0},
	{loader: 0},
	{Audio: 0},
	{Browser: 0},
	{Mouse: 0},
	{scoreArray: 0},
	{Touch: 0},
	{spawner: 0},
	{scoreNiveau: 0},
	{scoreNiveauFin: 0},
	{scoreNiveauFin_shadow: 0},
	{txtResetUserData: 0},
	{scoreIncrement: 0},
	{scoreIncrement_shadaws: 0},
	{Text: 0},
	{textNaration: 0},
	{loader_text: 0},
	{billBoard_spot: 0},
	{LocalStorage: 0},
	{scoreNiveauFinBest: 0},
	{scoreNiveauFinBest_shadow: 0},
	{Bulle_bestScore: 0},
	{BestScores: 0},
	{transi_hole: 0},
	{debug: 0},
	{textCadre: 0},
	{btnYes: 0},
	{btnNo: 0},
	{Particles: 0},
	{zoneMapClick: 0},
	{print: 0},
	{logo: 0},
	{volumMusic: 0},
	{bigBtn: 0},
	{state: 0},
	{tricks1: 0},
	{tricks2: 0},
	{niveau: 0},
	{nbNiveauMax: 0},
	{Score: 0},
	{ScoreToWin: 0},
	{totalScore: 0},
	{BestScore: 0},
	{Bestbeaten: 0},
	{PreviousBest: 0},
	{annimSpeed: 0},
	{photoSpeed: 0},
	{delayBTWphoto: 0},
	{endAnnimFinish: 0},
	{audioWorking: 0},
	{index: 0},
	{nbGood1: 0},
	{nbGood2: 0},
	{nbBad: 0},
	{picMarge: 0},
	{lastScoreSpawn: 0},
	{isGood: 0},
	{isFullScreen: 0},
	{canClick: 0},
	{saveTxtOut: 0},
	{infoTxtOut: 0},
	{musicTxtOut: 0},
	{cinematicVolum: 0},
	{sfxVolum: 0},
	{GamemusicVolum: 0},
	{musicVolum: 0},
	{masterVolum: 0},
	{VolumIndex: 0},
	{initVolumIndex: 0},
	{map_pos: 0},
	{max_map_pos: 0},
	{zoomSpeed: 0},
	{camSpeed: 0},
	{goToLevel: 0},
	{magUnlock: 0},
	{camDis: 0},
	{blopSoundIndex: 0},
	{lastHeight: 0},
	{magPage: 0},
	{maxPage: 0},
	{canTurnPage: 0},
	{page: 0}
];

self.InstanceType = {
	biilBoard_score: class extends self.I3DShapeInstance {},
	billboard_montain: class extends self.I3DShapeInstance {},
	billboard_sky: class extends self.I3DShapeInstance {},
	billboard_sun: class extends self.I3DShapeInstance {},
	SkyBoxBottom: class extends self.ISpriteInstance {},
	SkyBoxSide: class extends self.ISpriteInstance {},
	SkyBoxTop: class extends self.ISpriteInstance {},
	bulle: class extends self.ISpriteInstance {},
	lookat: class extends self.ISpriteInstance {},
	map_map: class extends self.ISpriteInstance {},
	map_mountain: class extends self.ISpriteInstance {},
	map_sun: class extends self.ISpriteInstance {},
	spot: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	spot_img: class extends self.ISpriteInstance {},
	LevelName: class extends self.ITextInstance {},
	gauge: class extends self.ISpriteInstance {},
	gaugeBack: class extends self.ISpriteInstance {},
	gaugePart: class extends self.ISpriteInstance {},
	TextTotalScore: class extends self.ITextInstance {},
	btnSave: class extends self.ISpriteInstance {},
	intro_: class extends self.ISpriteInstance {},
	intro_back: class extends self.ISpriteInstance {},
	intro_cloud: class extends self.ISpriteInstance {},
	intro_hawks: class extends self.ISpriteInstance {},
	intro_pony: class extends self.ISpriteInstance {},
	intro_proSkater: class extends self.ISpriteInstance {},
	intro_splash: class extends self.ISpriteInstance {},
	PlanDeTravail: class extends self.ISpriteInstance {},
	playNow: class extends self.ISpriteInstance {},
	pony: class extends self.ISpriteInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	btnWho: class extends self.ISpriteInstance {},
	btnMusic: class extends self.ISpriteInstance {},
	annim_banana: class extends self.ISpriteInstance {},
	push2begin: class extends self.ISpriteInstance {},
	PlanDeTravail6: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	score_shadow: class extends self.ITextInstance {},
	tricks: class extends self.ISpriteInstance {},
	flash: class extends self.ISpriteInstance {},
	photoShoot: class extends self.ISpriteInstance {},
	btnNext: class extends self.ISpriteInstance {},
	btnRepeat: class extends self.ISpriteInstance {},
	photo: class extends self.ISpriteInstance {},
	PlanDeTravail5: class extends self.ISpriteInstance {},
	push: class extends self.ISpriteInstance {},
	flecheD: class extends self.ISpriteInstance {},
	flecheG: class extends self.ISpriteInstance {},
	mag_1: class extends self.ISpriteInstance {},
	mag_2: class extends self.ISpriteInstance {},
	mag_3D_1: class extends self.ISpriteInstance {},
	mag_3D_2: class extends self.ISpriteInstance {},
	movingPage: class extends self.I3DShapeInstance {},
	movingPage1: class extends self.I3DShapeInstance {},
	movingPage2: class extends self.I3DShapeInstance {},
	btnClose: class extends self.ISpriteInstance {},
	inspirated_image: class extends self.ISpriteInstance {},
	introScinematic_1: class extends self.ISpriteInstance {},
	introScinematic_2: class extends self.ISpriteInstance {},
	story: class extends self.ITextInstance {},
	keyboard: class extends self.IInstance {},
	tricksPos: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Caméra3D: class extends self.IInstance {},
	ContrôleurDeLaTimeline: class extends self.IInstance {},
	PlanDeTravail4: class extends self.ISpriteInstance {},
	wasClicked: class extends self.IArrayInstance {},
	pic: class extends self.ISpriteInstance {},
	loader: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	scoreArray: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	spawner: class extends self.ISpriteInstance {},
	scoreNiveau: class extends self.ISpriteInstance {},
	scoreNiveauFin: class extends self.ITextInstance {},
	scoreNiveauFin_shadow: class extends self.ITextInstance {},
	txtResetUserData: class extends self.ITextInstance {},
	scoreIncrement: class extends self.ITextInstance {},
	scoreIncrement_shadaws: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	textNaration: class extends self.ITextInstance {},
	loader_text: class extends self.ITextInstance {},
	billBoard_spot: class extends self.I3DShapeInstance {},
	LocalStorage: class extends self.IInstance {},
	scoreNiveauFinBest: class extends self.ITextInstance {},
	scoreNiveauFinBest_shadow: class extends self.ITextInstance {},
	Bulle_bestScore: class extends self.ITextInstance {},
	BestScores: class extends self.IArrayInstance {},
	transi_hole: class extends self.ISpriteInstance {},
	debug: class extends self.ITextInstance {},
	textCadre: class extends self.ISpriteInstance {},
	btnYes: class extends self.ISpriteInstance {},
	btnNo: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	zoneMapClick: class extends self.ISpriteInstance {},
	print: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	volumMusic: class extends self.ITextInstance {},
	bigBtn: class extends self.ISpriteInstance {}
}